import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../../lib/api';
import { useState } from 'react';
import { ChevronDown, Filter } from 'lucide-react';
export default function EventsTab() {
    const [category, setCategory] = useState('');
    const [status, setStatus] = useState('');
    const [showFilters, setShowFilters] = useState(false);
    const { data: events, isLoading } = useQuery({
        queryKey: ['events', category, status],
        queryFn: () => apiClient.getEvents(20, 0, category || undefined, status || undefined),
    });
    const categories = ['crypto', 'sports', 'gaming', 'music', 'politics'];
    const statuses = ['active', 'pending', 'completed'];
    return (_jsxs("div", { className: "p-4 space-y-4", children: [_jsxs("button", { onClick: () => setShowFilters(!showFilters), className: "w-full bg-dark-card hover:bg-dark-card/80 text-white py-3 rounded-lg font-semibold flex items-center justify-between transition border border-dark-border", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(Filter, { size: 20 }), "Filters"] }), _jsx(ChevronDown, { size: 20, className: `transition ${showFilters ? 'rotate-180' : ''}` })] }), showFilters && (_jsxs("div", { className: "bg-dark-card rounded-lg p-4 border border-dark-border space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "text-sm text-gray-400 block mb-2", children: "Category" }), _jsxs("select", { value: category, onChange: (e) => setCategory(e.target.value), className: "w-full bg-dark-bg text-white rounded-lg px-3 py-2 border border-dark-border focus:outline-none focus:border-primary", children: [_jsx("option", { value: "", children: "All Categories" }), categories.map((cat) => (_jsx("option", { value: cat, children: cat.charAt(0).toUpperCase() + cat.slice(1) }, cat)))] })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm text-gray-400 block mb-2", children: "Status" }), _jsxs("select", { value: status, onChange: (e) => setStatus(e.target.value), className: "w-full bg-dark-bg text-white rounded-lg px-3 py-2 border border-dark-border focus:outline-none focus:border-primary", children: [_jsx("option", { value: "", children: "All Status" }), statuses.map((st) => (_jsx("option", { value: st, children: st.charAt(0).toUpperCase() + st.slice(1) }, st)))] })] })] })), _jsx("div", { className: "space-y-3", children: isLoading ? (_jsx("div", { className: "text-center py-8 text-gray-500", children: "Loading events..." })) : events?.events?.length ? (events.events.map((event) => (_jsxs("div", { className: "bg-dark-card rounded-lg p-4 border border-dark-border hover:border-primary transition cursor-pointer", children: [_jsxs("div", { className: "flex justify-between items-start mb-2", children: [_jsx("h3", { className: "font-semibold text-white flex-1", children: event.title }), _jsx("span", { className: `text-xs px-2 py-1 rounded-full font-semibold ${event.status === 'active'
                                        ? 'bg-green-500/20 text-success'
                                        : event.status === 'pending'
                                            ? 'bg-yellow-500/20 text-warning'
                                            : 'bg-gray-500/20 text-gray-300'}`, children: event.status })] }), _jsx("p", { className: "text-sm text-gray-400 mb-3", children: event.description }), _jsxs("div", { className: "grid grid-cols-3 gap-2 mb-3 text-sm", children: [_jsxs("div", { children: [_jsx("p", { className: "text-gray-500", children: "Entry Fee" }), _jsxs("p", { className: "font-semibold", children: ["\u20A6", event.entryFee.toLocaleString()] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-500", children: "Category" }), _jsx("p", { className: "font-semibold capitalize", children: event.category })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-500", children: "Participants" }), _jsx("p", { className: "font-semibold", children: event.participants })] })] }), _jsxs("div", { className: "flex gap-2 text-xs", children: [_jsxs("div", { className: "flex-1 bg-dark-bg rounded-lg p-2 text-center", children: [_jsx("p", { className: "text-gray-500", children: "YES" }), _jsx("p", { className: "font-bold text-success", children: event.yesVotes })] }), _jsxs("div", { className: "flex-1 bg-dark-bg rounded-lg p-2 text-center", children: [_jsx("p", { className: "text-gray-500", children: "NO" }), _jsx("p", { className: "font-bold text-danger", children: event.noVotes })] })] }), _jsx("button", { className: "w-full mt-3 bg-primary hover:bg-primary/90 text-white py-2 rounded-lg font-semibold transition", children: "View Details" })] }, event.id)))) : (_jsx("div", { className: "text-center py-8 text-gray-500", children: "No events found" })) })] }));
}
